language: perl
perl:
    - 5.18

before_install:
    - sudo apt-get install -y build-essential libmouse-perl liblog-log4perl-perl libjson-xs-perl libhttp-tiny-perl

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - /^release-.*$/
